module.exports = {
  config: {
    path: {
      title: 'gorename path',
      description: 'Set this if the gorename executable is not found within your PATH',
      type: 'string',
      "default": 'gorename'
    }
  },
  activate: function() {
    return new (require('./go-rename-view'));
  }
};

// ---
// generated by coffee-script 1.9.2
